### ISSUE TITLE
local mqtt broker must be set

### ISSUE THREAD

**Issue by tobit6795** [reinhard-brandstaedter/solarflow#13]
not exactly an issue with the code i guess, but what MQTT_HOST is expected in the env file?

i started the container the following way:

`docker run -d --restart=always --env-file .zendure_env -p 0.0.0.0:5000:5000 --name solarflow-statuspage rbrandstaedter/solarflow-statuspage:latest`

.zendure_env contains email + password from zendure app

`root@portainer:~# docker logs solarflow-statuspage --follow
2023-08-24 20:12:44,694:ERROR: You need a local MQTT broker set (environment variable MQTT_HOST)!
2023-08-24 20:12:46,496:ERROR: You need a local MQTT broker set (environment variable MQTT_HOST)!
2023-08-24 20:12:47,971:ERROR: You need a local MQTT broker set (environment variable MQTT_HOST)!
root@portainer:~#`

this way the container immediately shuts down after starting

I tested just for fun with my homeassistant mqtt broker, but couldn't see any messages coming in. with that configured i still got my data

![Screenshot 2023-08-24 222018](https://github.com/reinhard-brandstaedter/solarflow/assets/31254099/70fbbdee-35bb-4b9a-9206-eedc97dc6d9b)

Also it currently looks like i can not set any values with the webapp, but i guess thats because of the configuration?

EDIT: Probably the MQTT Host i created an dev account for? 
EDIT2: OK, got it, so my first assumption was right lol. I havent got any messages because my broker requires authentication. During my investigations i noticed that the master does not contain the same version you published on docker hub. which branch can i use to get it?

**Comment by reinhard-brandstaedter** [comment]
Sorry @tobit6795 , I have not set up a build pupeline yet. The docker image is built from the direct-control branch, which is intended to work with the sf-control script, using a local MQTT to provide data.
