### ISSUE TITLE
Howto retrieve Device_ID?

### ISSUE THREAD

**Issue by delco-1** [reinhard-brandstaedter/solarflow#5]
First of all, thanks for your work. Zendures documentation is incomplete and shallow. So a beginner like me has some trouble and therefor configuration problems. I'm using MQTT explorer too an after logging in to Zendures MQTT Broker with appkey and secret I only see the Brokers name "mqtt.zen-iot.com". nothing more. Can you please describe for dummies like me, how to configure MQTT explorer (see attachments for my config) an how to retrieve the "device ID". 
Thanks for your help.
![Screenshot 2023-07-17 112831](https://github.com/reinhard-brandstaedter/solarflow/assets/126969085/64c5a95e-318e-4044-b88e-70d6eef21215)
![Screenshot 2023-07-17 112140](https://github.com/reinhard-brandstaedter/solarflow/assets/126969085/965e0249-30f3-4f49-b4d5-440084a1bf09)
![Screenshot 2023-07-17 112535](https://github.com/reinhard-brandstaedter/solarflow/assets/126969085/f59b7b36-0c9e-4ee2-9075-2aa531dd56c7)

**Comment by reinhard-brandstaedter** [comment]
Hi @delco-1 ,
in MQTT exploer add your appkey as a topic like this ```<APPKEY>/#```. Once you connect you should see a topic tree now. The second level under your APPKEY is the device ID.

**Comment by delco-1** [comment]
That's it. :-)
Many thanks.
